### ISSUE TITLE
如何区分提交的用户?

### ISSUE THREAD

**Issue by linningmii** [kkxujq/leetcode#4]
方案:  [Qid].[github username].[文件后缀]

pre-commit hook中扫描非标准文件名并根据提交用户自动订正
对于现有文件尝试考虑人工修改，根据commit信息来做脚本自动改可能成本会比较高

**Comment by inJs** [comment]
@linningmii 没必要人工修改吧？增量就好了。

**Comment by kkxujq** [comment]
已按照推荐方案纳入[TODO](https://github.com/kkxujq/leetcode/issues/5)
